name: lava
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - atlite
  - gdal
  - geopandas
  - richdem
  - shapely
  - unidecode
  - pyyaml
  - pandas
  - matplotlib
  - numpy
  - pygadm
  - jupyter
  - ipython
  - ipykernel
  - openeo
  - pyrosm
  - fiona
  - requests
  - pyrosm
  - openpyxl
  - xdem
  - snakemake
  - pip            # ← ensure pip is installed so we can point at Git if needed
  - pip:
    - OSMPythonTools
    - distancerasters
    - geonamescache