name: lava
channels:
  - conda-forge
  - defaults
dependencies:
  - atlite
  - gdal
  - geopandas
  - richdem
  - shapely
  - unidecode
  - pyyaml
  - pandas
  - matplotlib
  - numpy
  - pygadm
  - jupyter
  - ipython
  - ipykernel
  - openeo
  - pyrosm
  - fiona
  - requests
  - pyrosm
  - openpyxl
  - pip            # ← ensure pip is installed so we can point at Git
  - pip:
    - git+https://github.com/m-dandrea/osm-python-tools.git@main#egg=osmpythontools
    - distancerasters
