name: lava
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - rasterio=1.3.8
  - gdal=3.7.2
  - richdem
  - shapely
  - unidecode
  - pyyaml
  - pandas
  - matplotlib
  - numpy
  - pygadm
  - shapely
  - jupyter
  - ipython
  - ipykernel
  - openeo
  - pyrosm
  - fiona
  - requests
  - pyrosm